name: Windows Build

on:
  push:
    branches:
      - main  # Dispara o workflow ao fazer push na branch 'main'
  pull_request:
    branches:
      - main  # Também dispara em PRs para a branch 'main'

jobs:
  build:
    runs-on: windows-latest  # Usa máquina Windows para build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Atualizado para v4

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Atualizado para v4
        with:
          node-version: '20.12.1'  # Define a versão exata do Node.js
          check-latest: true  # Garante a versão mais recente dentro do patch

      - name: Install dependencies
        run: npm install  # Instala todas as dependências

      - name: Build application
        run: npm run build  # Realiza o build com electron-builder

      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Atualizado para v4
        with:
          name: AzerothForge-build
          path: dist/*.exe  # Faz upload do executável gerado

      - name: Verify Node.js version
        run: node -v  # Verifica e exibe a versão instalada do Node.js
