name: Build Electron App

on:
  push:
    branches:
      - main  # Dispara o workflow ao fazer push na branch 'main'
  pull_request:
    branches:
      - main  # Também dispara ao abrir PRs para 'main'

jobs:
  build:
    runs-on: windows-latest  # Usa uma máquina Windows para compilar

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Clona o repositório

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.1'  # Define a versão do Node.js

      - name: Install dependencies
        run: npm install  # Instala todas as dependências

      - name: Build application
        run: npm run build  # Executa o build com electron-builder

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AzerothForge-build
          path: dist/*.exe  # Faz upload do executável gerado
